# Generated by Django 4.2.27 on 2026-01-10 16:51

from django.db import migrations
import django_full_kit.django_full_kit.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=django_full_kit.django_full_kit.models.PhoneNumberField(max_length=16, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
